//var TestBot = require('./lib/bot')
var Game = require('./lib/game')
console.log(Game)
var newGame = new Game('p1', 'p2')

//console.log(newGame)
newGame.placePiece(6)

//newGame.placePiece(7)
//newGame.printBoard()
// newGame.placePiece(1)
// newGame.printBoard()
// newGame.placePiece(2)
// newGame.printBoard()
// newGame.placePiece(2)
// newGame.printBoard()
// newGame.placePiece(2)
// newGame.placePiece(3)
// newGame.printBoard()
// newGame.placePiece(3)
// newGame.placePiece(3)
// newGame.printBoard()
// newGame.placePiece(3)
// newGame.printBoard()
// newGame.placePiece(3)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.placePiece(5)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()

// newGame.placePiece(2)
// newGame.printBoard()

// vertical

// newGame.printBoard()
// newGame.placePiece(5)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.printBoard()
// newGame.placePiece(5)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()
// newGame.printBoard()
// newGame.placePiece(5)
// newGame.printBoard()
// newGame.placePiece(4)
// newGame.printBoard()